# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

development:
  mark_overdue_tasks:
    class: MarkOverdueTasksJob
    queue: scheduled
    schedule: every hour

production:
  mark_overdue_tasks:
    class: MarkOverdueTasksJob
    queue: scheduled
    schedule: every hour
